### ISSUE TITLE
PlexRecs not working

### ISSUE THREAD

**Issue by amokster88** [nwithan8/PlexRecs#13]
`(recs_venv) amolak@homeserver:~/python_scripts/PlexRecs$ python3 run.py
Traceback (most recent call last):
  File "/home/amolak/python_scripts/PlexRecs/recs_venv/lib/python3.10/site-packages/discord/ext/commands/bot.py", line 606, in _load_from_module_spec
    spec.loader.exec_module(lib)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/amolak/python_scripts/PlexRecs/PlexRecs.py", line 11, in <module>
    import modules.imdb_connector as imdb
  File "/home/amolak/python_scripts/PlexRecs/modules/imdb_connector.py", line 1, in <module>
    from imdbpie import ImdbFacade
  File "/home/amolak/python_scripts/PlexRecs/recs_venv/lib/python3.10/site-packages/imdbpie/__init__.py", line 2, in <module>
    from .imdbpie import Imdb  # noqa
  File "/home/amolak/python_scripts/PlexRecs/recs_venv/lib/python3.10/site-packages/imdbpie/imdbpie.py", line 17, in <module>
    from .auth import Auth
  File "/home/amolak/python_scripts/PlexRecs/recs_venv/lib/python3.10/site-packages/imdbpie/auth.py", line 13, in <module>
    import diskcache
  File "/home/amolak/python_scripts/PlexRecs/recs_venv/lib/python3.10/site-packages/diskcache/__init__.py", line 5, in <module>
    from .fanout import FanoutCache
  File "/home/amolak/python_scripts/PlexRecs/recs_venv/lib/python3.10/site-packages/diskcache/fanout.py", line 10, in <module>
    from .persistent import Deque, Index
  File "/home/amolak/python_scripts/PlexRecs/recs_venv/lib/python3.10/site-packages/diskcache/persistent.py", line 8, in <module>
    from collections import MutableMapping, OrderedDict, Sequence
ImportError: cannot import name 'MutableMapping' from 'collections' (/usr/lib/python3.10/collections/__init__.py)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/amolak/python_scripts/PlexRecs/run.py", line 20, in <module>
    bot.load_extension(ext)
  File "/home/amolak/python_scripts/PlexRecs/recs_venv/lib/python3.10/site-packages/discord/ext/commands/bot.py", line 678, in load_extension
    self._load_from_module_spec(spec, name)
  File "/home/amolak/python_scripts/PlexRecs/recs_venv/lib/python3.10/site-packages/discord/ext/commands/bot.py", line 609, in _load_from_module_spec
    raise errors.ExtensionFailed(key, e) from e
discord.ext.commands.errors.ExtensionFailed: Extension 'PlexRecs' raised an error: ImportError: cannot import name 'MutableMapping' from 'collections' (/usr/lib/python3.10/collections/__init__.py)`

**Comment by nwithan8** [comment]
https://stackoverflow.com/questions/70870041/cannot-import-name-mutablemapping-from-collections

Bot is not compatible with Python 3.10 currently

**Comment by amokster88** [comment]
Any ETA on compatibility with 3.10

**Comment by nwithan8** [comment]
@amokster88 Fixed.
